name:  CatchMe
main:  com.fuzzycraft.fuzzy.CatchMe
version:  1.2
permissions:
    catchee:
        description: Let's a player become a catchee (become IT)
        default: true
    catcher:
        description: Let's a player catch a catchee (catch who is IT)
        default: true